// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChAP-2XptIZ5m7pzhIIjHBD-6CQ_9Kw-A',
    appId: '1:827065549014:web:3c4bafb96b817185714977',
    messagingSenderId: '827065549014',
    projectId: 'project1-8ed48',
    authDomain: 'project1-8ed48.firebaseapp.com',
    storageBucket: 'project1-8ed48.appspot.com',
    measurementId: 'G-DNY4PTHP9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4mLsKwv2zzzMF3RkfblJxv6mJX-Z-2Us',
    appId: '1:827065549014:android:9cd1032761164da7714977',
    messagingSenderId: '827065549014',
    projectId: 'project1-8ed48',
    storageBucket: 'project1-8ed48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwArcAGXMlZNL1Rsx98WEWOb-HNeccj0',
    appId: '1:827065549014:ios:e9ed814c394398ab714977',
    messagingSenderId: '827065549014',
    projectId: 'project1-8ed48',
    storageBucket: 'project1-8ed48.appspot.com',
    iosBundleId: 'com.example.firebasepr202210e',
  );
}
